### PR TITLE
Add testnet version bytes to extended keys, close #67

### LINKED ISSUE #67: Testnet support in bip32
https://github.com/komputing/KEthereum/blob/3b69fde6d80ef6e80a632b756a93d5def5998179/bip32/src/main/kotlin/org/kethereum/bip32/model/Constants.kt#L10

The Testnet network could be supported in bip32's ExtendedKey deserialization:
```
internal val xprvTestnet = byteArrayOf(0x04, 0x88.toByte(), 0xAD.toByte(), 0xE4.toByte())
internal val xpubTestnet = byteArrayOf(0x04, 0x35.toByte(), 0x87.toByte(), 0xCF.toByte())
```

And it could be considered in `XPriv.toExtendedKey()` method:
```
    val hasPrivate = when {
        Arrays.equals(type, xprv) -> true
        Arrays.equals(type, xprvTestnet) -> true
        Arrays.equals(type, xpub) -> false
        Arrays.equals(type, xpubTestnet) -> false
        else -> throw KeyException("invalid magic number for an extended key")
    }
```

### PR DESCRIPTION
**Pull request by mahdi13**

### CODE REVIEW

**Comment by ligi** [comment]
thanks! LGTM - kindly asking @mirceanis to also have a look as he was doing the original BIP32 PR

**Comment by mirceanis** [comment]
I can take a look tomorrow

**Comment by ligi** [comment]
That would be much appreciated!

**Comment by mirceanis** [comment]
Code looks ok, there is a breaking change for people who are directly instantiating `ExtendedKey` or using equality tests on preexisting ones and that should be mentioned in release notes when released.

Also, what is the use of this? It would be nice to see a description on the PR.

The reason that testnet values weren't added from the beginning is that the "testnet" is a bitcoin one and had no apparent relation to ethereum. It's also possible I missed it back then.
Is there a use-case now, @mahdi13 ?

**Comment by ligi** [comment]
Thanks for the review. I think it is good to also support bitcoin and respect the standard. Also think to extract the code to a new repo into Komputing like KBip32 to decouple from Ethereum

**Comment by mirceanis** [comment]
> I think it is good to also support bitcoin and respect the standard. 

right, my question is out of curiosity, not a critique of the PR.

> Also think to extract the code to a new repo into Komputing like KBip32 to decouple from Ethereum

sounds like a very good idea. Based on past experience, this should also be correlated with a release in KEthereum where the bip32 module is removed, to avoid getting a "duplicated classes" error when compiling for android.

**Comment by mahdi13** [comment]
@mirceanis I agree with you, I don't see any relationship between bitocin's testnet and ethereum. I only suggested it because it was part of the official bip-0032 proposal.
Thanks for your great toolchain, I've been using this repository in many of my organization's project. Not only about ethereum, but I've also chosen this library for implementing bitcoin, ripple, and other cryptocurrencies tools. I see great potential on this code to be expanded to cover more cryptocurrencies.

**Pull request merged**
